-- Retention in the monolith model. While history is still one coarse monolith spanning the retention
-- horizon, retain() cannot drop it (a partition that straddles the horizon survives): retention is
-- suspended over coarse history. Once refine() splits the monolith into fine children, retain() drops
-- the aged ones below the horizon and keeps the rest.
create extension if not exists pgtap;

begin;
select plan(4);

create table public.rt7 (id bigint generated by default as identity primary key, payload text);
insert into public.rt7 (payload) select 'x' from generate_series(1, 50000);   -- ids 1..50000
select pgpm.transmute('public.rt7', 'id', 10000);   -- monolith [0, 60000) -- coarse, 6 steps; paused
select pgpm.obtain('public.rt7');
insert into public.rt7 (id, payload) values (65000, 'frontier');   -- advance frontier past B=60000 -> monolith frozen
update pgpm.config set retain = '30000' where parent_table = 'public.rt7'::regclass;

select is(
  pgpm.retain('public.rt7'),
  0, 'retention is suspended over the coarse monolith (a partition spanning the horizon cannot be dropped)');

select cmp_ok(
  pgpm.refine_history('public.rt7'),
  '>', 0, 'refine splits the monolith into fine children');

select cmp_ok(
  pgpm.retain('public.rt7'),
  '>', 0, 'after refine, retention drops the aged fine children below the horizon');

select ok(
  to_regclass('public.rt7_p' || lpad('0', 19, '0')) is null
    and to_regclass('public.rt7_p' || lpad('50000', 19, '0')) is not null,
  'the oldest fine child (below the horizon) is dropped; a within-horizon child survives');

select * from finish();
rollback;
