-- status() surfaces the refinement backlog (REDESIGN.md section 14): coarse_partitions counts the
-- un-refined coarse children (the monolith, and any coarser children from a partial refinement) and
-- history_unrefined flags that pruning and fine retention are suspended over that span. After refine()
-- splits the monolith into fine children, both go to zero/false.
create extension if not exists pgtap;
begin;
select plan(4);

create table public.st (id bigint generated by default as identity primary key, payload text);
insert into public.st (payload) select 'x' from generate_series(1, 50000);
select pgpm.transmute('public.st', 'id', 10000);   -- monolith [0, 60000) -- coarse, 6 steps
select pgpm.obtain('public.st');

select is(
  (select coarse_partitions from pgpm.status() where parent = 'public.st'::regclass),
  1::bigint, 'status() reports the coarse monolith as one coarse partition (the refinement backlog)');

select ok(
  (select history_unrefined from pgpm.status() where parent = 'public.st'::regclass),
  'status() flags history as unrefined while the monolith is coarse');

-- freeze the monolith and refine it
insert into public.st (id, payload) values (65000, 'frontier');
select pgpm.refine_history('public.st');

select is(
  (select coarse_partitions from pgpm.status() where parent = 'public.st'::regclass),
  0::bigint, 'after refine, no coarse partitions remain');

select ok(
  not (select history_unrefined from pgpm.status() where parent = 'public.st'::regclass),
  'after refine, history_unrefined is false (the backlog is cleared)');

select * from finish();
rollback;
